[package]
name = "rotta_rs"
version = "0.0.3"
edition = "2024"
license = "Apache-2.0"
description = "an AI framework with rust language"

[dependencies]
rand = "0.9.1"
rand_distr = "0.5.1"

[dependencies.uuid]
version = "1.17.0"
# Lets you generate random UUIDs
features = [
    "v4",
]
