[package]
name = "rotta-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
rand = "0.9.1"
rand_distr = "0.5.1"

[dependencies.uuid]
version = "1.17.0"
# Lets you generate random UUIDs
features = [
    "v4",
]